"""Add admin table

Revision ID: 79750360ab68
Revises: 29f4938c4335
Create Date: 2025-05-21 16:18:49.109852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79750360ab68'
down_revision = '29f4938c4335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###
